### PR TITLE
Stubs 1

### PR DESCRIPTION
**Pull request by CandyCrystal**

### CODE REVIEW

**Comment by 21aslade** [comment]
We've been using the convention of `Main` for the only room in an area, and that could also apply to areas with just two rooms and an obvious main one (like Minish Village); other than that it looks good.

**Comment by CandyCrystal** [comment]
Alright! i have now edited them!

**Comment by 21aslade** [comment]
Applies to lake_hylia too, sorry for not being clear

**Comment by CandyCrystal** [comment]
Done, no worries :)

**Pull request merged**
